In [1]:
import os
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from matplotlib import pyplot as plt

# pd.set_option('display.max_rows', 500)
# pd.set_option('display.max_columns', 500)
# pd.set_option('display.width', 1000)

%matplotlib inline

In [2]:
Inpu_nms = {
    "DEPTH",
    "TRANY",
    "PORV",
    "TRANX",
    "PERMZ",
    "TRANZ",
    "PORO",
    "SATNUM",
    "PERMY",
    "PERMX",
}
data = {}


def np_load(input_nm, file_nm, rp):
    try:
        d = np.load(rp, allow_pickle=True)
        return d  # Always load data
    except ValueError as e:
        print(input_nm, file_nm, e)
        raise e


for root, dirs, files in os.walk("./origen_interview_data/", topdown=False):
    root_parts = root.split("/")
    assert len(root_parts) == 3, "too many parts in %s" % root
    input_name = root_parts[-1]

    # Process only if the input_name is in the specified set
    if input_name in Inpu_nms:
        for file in filter(".DS_Store".__ne__, files):
            file_parts = file.split(".")
            assert len(file_parts) == 2, "unexpected filename pattern: %s" % file
            dataset_name = file_parts[0]
            realpath = os.path.realpath(os.path.join(root, file))
            # Load data and store it in the dictionary
            data[input_name, dataset_name] = np_load(input_name, file, realpath)
            print("Loaded data for input %s, dataset %s" % (input_name, dataset_name))

Loaded data for input DEPTH, dataset sim196_depth
Loaded data for input DEPTH, dataset sim475_depth
Loaded data for input DEPTH, dataset sim369_depth
Loaded data for input DEPTH, dataset sim60_depth
Loaded data for input DEPTH, dataset sim125_depth
Loaded data for input DEPTH, dataset sim313_depth
Loaded data for input DEPTH, dataset sim255_depth
Loaded data for input DEPTH, dataset sim241_depth
Loaded data for input DEPTH, dataset sim288_depth
Loaded data for input DEPTH, dataset sim307_depth
Loaded data for input DEPTH, dataset sim131_depth
Loaded data for input DEPTH, dataset sim74_depth
Loaded data for input DEPTH, dataset sim461_depth
Loaded data for input DEPTH, dataset sim182_depth
Loaded data for input DEPTH, dataset sim260_depth
Loaded data for input DEPTH, dataset sim110_depth
Loaded data for input DEPTH, dataset sim326_depth
Loaded data for input DEPTH, dataset sim55_depth
Loaded data for input DEPTH, dataset sim440_depth
Loaded data for input DEPTH, dataset sim489_depth
Loa

In [3]:
data.items()

dict_items([(('DEPTH', 'sim196_depth'), array([ 9010.   ,  9062.9  ,  9115.798, ..., 10419.86 , 10472.76 ,
       10525.66 ], dtype=float32)), (('DEPTH', 'sim475_depth'), array([ 9010.   ,  9062.9  ,  9115.798, ..., 10419.86 , 10472.76 ,
       10525.66 ], dtype=float32)), (('DEPTH', 'sim369_depth'), array([ 9010.   ,  9062.9  ,  9115.798, ..., 10419.86 , 10472.76 ,
       10525.66 ], dtype=float32)), (('DEPTH', 'sim60_depth'), array([ 9010.   ,  9062.9  ,  9115.798, ..., 10419.86 , 10472.76 ,
       10525.66 ], dtype=float32)), (('DEPTH', 'sim125_depth'), array([ 9010.   ,  9062.9  ,  9115.798, ..., 10419.86 , 10472.76 ,
       10525.66 ], dtype=float32)), (('DEPTH', 'sim313_depth'), array([ 9010.   ,  9062.9  ,  9115.798, ..., 10419.86 , 10472.76 ,
       10525.66 ], dtype=float32)), (('DEPTH', 'sim255_depth'), array([ 9010.   ,  9062.9  ,  9115.798, ..., 10419.86 , 10472.76 ,
       10525.66 ], dtype=float32)), (('DEPTH', 'sim241_depth'), array([ 9010.   ,  9062.9  ,  9115.798, ...,

In [4]:
# for k, v in data.items():
#     # print("key: %s, value: %s" % (k, v))
#     # print(v.shape)
#     print(k)

In [5]:
len(data)

5000

In [4]:
target_data = {}
target_names = {"BHP", "WOPR"}


def np_load(input_nm, file_nm, rp):
    try:
        d = np.load(rp, allow_pickle=True)
        if input_nm in target_names:  # Save data only for specified input_nm
            if input_nm in target_names:
                # d = d.reshape(15, 25, 24)
                return d
    except ValueError as e:
        print(input_nm, file_nm, e)
        raise e


for root, dirs, files in os.walk("./origen_interview_data/", topdown=False):
    root_parts = root.split("/")
    assert len(root_parts) == 3, "too many parts in %s" % root
    input_name = root_parts[-1]

    # Print "processing input" only for specified input_nm
    if input_name in target_names:
        for file in filter(".DS_Store".__ne__, files):
            file_parts = file.split(".")
            assert len(file_parts) == 2, "unexpected filename pattern: %s" % file
            dataset_name = file_parts[0]
            realpath = os.path.realpath(os.path.join(root, file))
            # Print "loading" only for specified input_nm
            # print("loading %s file %s" % (input_name, dataset_name))
            target_data[input_name, dataset_name] = np_load(input_name, file, realpath)

In [5]:
len(target_data.keys())

1000

In [9]:
for k, v in target_data.items():
    # print("key: %s, value: %s" % (k, v))
    print(v.shape)
    # print(k)

(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(300, 7)
(

In [184]:
X = []
y = []

for key, value in data.items():
    input_data, _ = key
    X.append(value)  # Flatten the input data

for key, value in target_data.items():
    taget_data, _ = key
    y.append(value)

In [200]:
import numpy as np

# Create 1000 target variables with shape (300, 7)
num_targets = 1000
target_shape = (300, 7)
target_keys = ["target_" + str(i) for i in range(num_targets)]  # Creating column names
target_data = {key: np.random.rand(*target_shape) for key in target_data}

# Create 6000 input variables with shape (15, 25, 24)
num_inputs = 6000
input_shape = (15, 25, 24)
input_keys = ["input_" + str(i) for i in range(num_inputs)]  # Creating column names
input_data = {key: np.random.rand(*input_shape) for key in data}

# Append values to X and y lists
X = [value for key, value in input_data.items()]
y = [value for key, value in target_data.items()]

# Print the shapes of the first target and input variables as examples
print("Input shape:", X[0].shape)
print("Target shape:", y[0].shape)

Input shape: (15, 25, 24)
Target shape: (300, 7)


In [210]:
# X = np.array(X)

In [212]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models

# Assuming you have loaded your data into X (input) and y (target)
# X should have shape (6000, 15, 25, 24)
# y should have shape (1000, 300, 7)
X = np.array(X)
y = np.array(y)

# Reshape input data to include the depth dimension (1)
X_reshaped = X.reshape((X.shape[0], X.shape[1], X.shape[2], X.shape[3], 1))

# Define the 3D CNN model
model = models.Sequential()
model.add(
    layers.Conv3D(
        32, (3, 3, 3), activation="relu", input_shape=(6000, 15, 25, 24), padding="same"
    )
)
model.add(layers.MaxPooling3D((2, 2, 2)))
model.add(layers.Conv3D(64, (3, 3, 3), activation="relu", padding="same"))
model.add(layers.MaxPooling3D((2, 2, 2)))
model.add(layers.Conv3D(128, (3, 3, 3), activation="relu", padding="same"))
model.add(layers.Flatten())
model.add(layers.Dense(300, activation="relu"))
model.add(
    layers.Dense(7, activation="linear")
)  # Adjust activation based on your problem

# Reshape input data to include the depth dimension (1)
X_reshaped = X.reshape((X.shape[0], X.shape[1], X.shape[2], X.shape[3], 1))

# Compile the model
model.compile(optimizer="adam", loss="mean_squared_error", metrics=["mae"])

# Train the model
model.fit(X_reshaped, y, epochs=10, batch_size=32, validation_split=0.2)

ValueError: Data cardinality is ambiguous:
  x sizes: 4800
  y sizes: 1000
Make sure all arrays contain the same number of samples.

In [231]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models

# Assuming you have loaded your data into X (input) and y (target)
# X should have shape (6000, 15, 25, 24)
# y should have shape (1000, 300, 7)

# Convert input data (X) and target data (y) to NumPy arrays
X = np.array(X)
y = np.array(y)

# Reshape input data to include the depth dimension (1)
X_train = np.array(X_train)
X_train = np.reshape(
    X_train, (X_train.shape[0], X_train.shape[1], X_train.shape[2], X_train.shape[3], 1)
)

# Split into train and eval sets
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=300, random_state=42
)

model = models.Sequential()
model.add(
    layers.Conv3D(
        32, (3, 3, 3), activation="relu", input_shape=(15, 25, 24, 1), padding="same"
    )
)
model.add(layers.MaxPooling3D((2, 2, 2)))
model.add(layers.Conv3D(64, (3, 3, 3), activation="relu", padding="same"))
model.add(layers.MaxPooling3D((2, 2, 2)))
model.add(layers.Conv3D(128, (3, 3, 3), activation="relu", padding="same"))
model.add(layers.Flatten())
model.add(layers.Dense(300, activation="relu"))
model.add(
    layers.Dense(300 * 7, activation="linear")
)  # Adjust activation based on your problem

# Reshape output to match target data shape
model.add(layers.Reshape((300, 7)))

# Compile the model
model.compile(optimizer="adam", loss="mean_squared_error", metrics=["mae"])
# Iterate through the data in chunks


# Assuming you have split your data into training and validation sets
# Adjust the split ratio as needed
validation_split = 0.2
split_index = int(len(X) * (1 - validation_split))

X_train, X_val = X_reshaped[:split_index], X_reshaped[split_index:]
y_train, y_val = y[:split_index], y[split_index:]

# Ensure the shapes match
assert (
    X_val.shape[0] == y_val.shape[0]
), "Mismatch in the number of samples between X_val and y_val"

# Convert to numpy arrays (if not already)
X_val = np.array(X_val)
y_val = np.array(y_val)

# Evaluate the model on the validation set
val_loss, val_mae = model.evaluate(X_val, y_val, verbose=0)

# Print the validation loss and metric
print(f"Validation Loss: {val_loss:.4f}, Validation MAE: {val_mae:.4f}")

batch_size = 8  # Choose an appropriate batch size
epochs = 10

# Training loop
for epoch in range(epochs):
    print(f"Epoch {epoch + 1}/{epochs}")
    for i in range(0, len(X_train), batch_size):
        X_batch = X_train[i : i + batch_size]
        y_batch = y_train[i : i + batch_size]

        # Ensure both X_batch and y_batch have the same number of samples
        assert X_batch.shape[0] == y_batch.shape[0], "Mismatch in the number of samples"

        # Train the model on the current batch
        model.train_on_batch(X_batch, y_batch)

    # Evaluate the model on the validation set after each epoch
    val_loss, val_mae = model.evaluate(X_val, y_val, verbose=0)
    print(f"Validation Loss: {val_loss:.4f}, Validation MAE: {val_mae:.4f}")

AssertionError: Mismatch in the number of samples between X_val and y_val

In [229]:
# split_index = int(len(X) * (1 - validation_split))

# X_train, X_val = X[:split_index], X[split_index:]
# y_train, y_val = y[:split_index], y[split_index:]

X_train = np.array(X_train)
X_train = np.reshape(
    X_train, (X_train.shape[0], X_train.shape[1], X_train.shape[2], X_train.shape[3], 1)
)

# Split into train and eval sets
X_train_split, X_eval, y_train_split, y_eval = train_test_split(
    X_train, y_train, test_size=300, random_state=42
)

# # Randomly choose 700 indices
# selected_indices = np.random.choice(X_train.shape[0], 700, replace=False)
# selected_indices_y = np.random.choice(y_train.shape[0], 700, replace=False)

# # Select the corresponding samples
# X_train = X_train[selected_indices]
# y_train = y_train[selected_indices_y]

# Verify the shape
print("X_train_selected shape:", X_train_selected.shape)
# Convert to numpy arrays (if not already)
X_train = np.array(X_train)
y_train = np.array(y_train)
X_eval = np.array(X_eval)
y_eval = np.array(y_eval)
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_val shape:", X_val.shape)
print("y_val shape:", y_val.shape)

X_train_selected shape: (700, 15, 25, 24)
X_train shape: (700, 15, 25, 24, 1)
y_train shape: (700, 300, 7)
X_val shape: (1200, 15, 25, 24)
y_val shape: (0, 300, 7)


In [59]:
# import torch
# import torch.nn as nn
# import torch.optim as optim
# from torch.utils.data import Dataset, DataLoader
# import os
# import numpy as np

# # Define your CNN model
# class CNNModel(nn.Module):
#     def __init__(self):
#         super(CNNModel, self).__init__()
#         # Modify the architecture based on your requirements
#         self.conv1 = nn.Conv3d(in_channels=15, out_channels=32, kernel_size=3)
#         self.pool = nn.MaxPool3d(kernel_size=2, stride=2)
#         self.fc1 = nn.Linear(32 * 5 * 4 * 4, 128)
#         self.fc2 = nn.Linear(128, 1)  # Assuming a single output for WOPR

#     def forward(self, x):
#         x = self.pool(F.relu(self.conv1(x)))
#         x = x.view(-1, 32 * 5 * 4 * 4)
#         x = F.relu(self.fc1(x))
#         x = self.fc2(x)
#         return x

# # Assuming 'data' is your loaded dictionary
# class CustomDataset(Dataset):
#     def __init__(self, data_dict, transform=None):
#         self.data_dict = data_dict
#         self.transform = transform
#         self.keys = list(data_dict.keys())

#     def __len__(self):
#         return len(self.keys)

#     def __getitem__(self, idx):
#         key = self.keys[idx]
#         data_3d = self.data_dict[key]
#         data_1d = load_1d_data(key)

#         if self.transform:
#             data_3d = self.transform(data_3d)

#         return data_3d, data_1d

# def load_1d_data(key):
#     # Placeholder function, replace with actual logic
#     return np.random.rand(24)

# # Initialize the model, loss function, and optimizer
# model = CNNModel()
# criterion = nn.MSELoss()
# optimizer = optim.Adam(model.parameters(), lr=0.001)

# # Create the dataset and dataloader
# dataset = CustomDataset(data)
# dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

# # Training loop
# num_epochs = 10
# for epoch in range(num_epochs):
#     for batch_idx, (data_3d, data_1d) in enumerate(dataloader):
#         # Convert data to torch tensors
#         data_3d = torch.FloatTensor(data_3d)
#         data_1d = torch.FloatTensor(data_1d)

#         # Forward pass
#         outputs = model(data_3d)

#         # Assuming you have WOPR labels, modify accordingly
#         labels = torch.FloatTensor(load_labels_for_batch(batch_idx))

#         # Compute the loss
#         loss = criterion(outputs, labels)

#         # Backward and optimize
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()

#         if (batch_idx + 1) % 10 == 0:
#             print(f'Epoch [{epoch+1}/{num_epochs}], Step [{batch_idx+1}/{len(dataloader)}], Loss: {loss.item():.4f}')

# # Assuming you have a function to load labels for each batch
# def load_labels_for_batch(batch_idx):
#     # Placeholder function, replace with actual logic
#     return np.random.rand(32)

In [60]:
# target_names = {"BHP", "WOPR"}
# data = {}

# def np_load(input_nm, file_nm, rp):
#     try:
#         d = np.load(rp, allow_pickle=True)
#         if input_nm in target_names:
#             data[input_nm, file_nm] = d  # Include only "BHP" and "WOPR" data
#         # else:
#         #     d = d.reshape(15, 25, 24)
#         #     data[input_nm, file_nm] = d  # Reshape and include other data
#         return d
#     except ValueError as e:
#         print(input_nm, file_nm, e)
#         raise e

# for root, dirs, files in os.walk("./origen_interview_data/", topdown=False):
#     root_parts = root.split("/")
#     assert len(root_parts) == 3, "too many parts in %s" % root
#     input_name = root_parts[-1]
#     for file in filter(".DS_Store".__ne__, files):
#         file_parts = file.split(".")
#         assert len(file_parts) == 2, "unexpected filename pattern: %s" % file
#         dataset_name = file_parts[0]
#         realpath = os.path.realpath(os.path.join(root, file))
#         np_load(input_name, dataset_name, realpath)

In [61]:
# import torch
# import torch.nn as nn

# class CombinedModel(nn.Module):
#     def __init__(self, num_3d_channels, num_1d_features):
#         super(CombinedModel, self).__init__()

#         # Define CNN layers for 3D data
#         self.cnn_layers = nn.Sequential(
#             # Define your CNN layers here
#         )

#         # Define FNN layers for 1D data
#         self.fnn_layers = nn.Sequential(
#             # Define your FNN layers here
#         )

#         # Fusion layer for combining 3D and 1D features
#         self.fusion_layer = nn.Linear(in_features=num_3d_channels + num_1d_features, out_features=256)

#         # Output layer
#         self.output_layer = nn.Linear(in_features=256, out_features=1)

#     def forward(self, x_3d, x_1d):
#         # Process 3D data through CNN layers
#         x_3d = self.cnn_layers(x_3d)

#         # Process 1D data through FNN layers
#         x_1d = self.fnn_layers(x_1d)

#         # Concatenate 3D and 1D features
#         combined_features = torch.cat((x_3d, x_1d), dim=1)

#         # Fusion layer
#         fused_features = torch.relu(self.fusion_layer(combined_features))

#         # Output layer
#         output = self.output_layer(fused_features)

#         return output

# # Instantiate the model with the appropriate number of 3D channels and 1D features
# model = CombinedModel(num_3d_channels=your_num_3d_channels, num_1d_features=your_num_1d_features)

# # Define your loss function and optimizer
# criterion = nn.MSELoss()
# optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# # Training loop, validation, and testing can be implemented based on your specific requirements.

In [62]:
# # Assuming 'data' is your dictionary
# filtered_data = {key: value for key, value in data.items()}

# # Extract the target arrays for 'WOPR' and 'BHP'
# target_WOPR = wopr_datasets
# target_BHP = bhp_datasets

# # Check if target arrays are present
# if target_WOPR is not None and target_BHP is not None:
#     # Unpack the filtered data into keys and arrays
#     keys, arrays = zip(*filtered_data.items())

#     # Convert NumPy arrays to tensors
#     tensor_arrays = [tf.convert_to_tensor(array) for array in arrays]

#     # Stack along a new axis to create a 4D tensor
#     input_data = tf.stack(tensor_arrays, axis=-1)
#     input_data_shape = tf.shape(input_data)
#     input_data_size = tf.size(input_data)


#     # Reshape to (batch_size, depth, height, width, channels)
#     # input_data = tf.reshape(input_data, [1, 15, 25, 24, len(arrays)])

#     # Create a simple deep learning model using TensorFlow
#     model = tf.keras.Sequential([
#         tf.keras.layers.Conv3D(32, (3, 3, 3), activation='relu', input_shape=(15, 25, 24, len(arrays))),
#         tf.keras.layers.MaxPooling3D((2, 2, 2)),
#         tf.keras.layers.Flatten(),
#         tf.keras.layers.Dense(64, activation='relu'),
#         tf.keras.layers.Dense(1, activation='linear')  # Adjust the output layer based on your task
#     ])

#     # Compile the model
#     model.compile(optimizer='adam', loss='mean_squared_error')  # Adjust the loss based on your task

#     # Split the data into training and testing sets
#     train_data, test_data, y_train, y_test = train_test_split(input_data.numpy(), target_WOPR, test_size=0.2, random_state=42)

#     # Normalize the data
#     scaler = StandardScaler()
#     train_data = scaler.fit_transform(train_data.reshape(-1, 15, 25, 24, len(arrays))).reshape(train_data.shape)
#     test_data = scaler.transform(test_data.reshape(-1, 15, 25, 24, len(arrays))).reshape(test_data.shape)

#     # Train the model
#     model.fit(train_data, y_train, epochs=10, validation_data=(test_data, y_test))
# else:
#     print("Target arrays 'WOPR' and 'BHP' are missing.")

In [63]:
# import os
# import numpy as np
# import tensorflow as tf
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler

# # Assuming 'data' is your dictionary
# filtered_data = {key: value for key, value in data.items()}

# # Extract the target arrays for 'WOPR' and 'BHP'
# target_WOPR = wopr_datasets
# target_BHP = bhp_datasets

# # Check if target arrays are present
# # if target_WOPR is not None and target_BHP is not None:
#     # Unpack the filtered data into keys and arrays
# keys, arrays = zip(*filtered_data.items())

# # Convert NumPy arrays to tensors
# tensor_arrays = [tf.convert_to_tensor(array) for array in arrays]

# # Concatenate tensors along a new axis to create a 4D tensor
# input_data = tf.stack(tensor_arrays, axis=-1)

# # Create a simple deep learning model using TensorFlow
# model = tf.keras.Sequential([
#     tf.keras.layers.Conv3D(32, (3, 3, 3), activation='relu', input_shape=input_data.shape[1:]),
#     tf.keras.layers.MaxPooling3D((2, 2, 2)),
#     tf.keras.layers.Flatten(),
#     tf.keras.layers.Dense(64, activation='relu'),
#     tf.keras.layers.Dense(1, activation='linear')  # Adjust the output layer based on your task
# ])

# # Compile the model
# model.compile(optimizer='adam', loss='mean_squared_error')  # Adjust the loss based on your task

# # Split the data into training and testing sets
# train_data, test_data, y_train, y_test = train_test_split(input_data.numpy(), target_WOPR, test_size=0.2, random_state=42)

# # Normalize the data
# scaler = StandardScaler()
# train_data = scaler.fit_transform(train_data.reshape(-1, input_data.shape[-1])).reshape(train_data.shape)
# test_data = scaler.transform(test_data.reshape(-1, input_data.shape[-1])).reshape(test_data.shape)

# # Train the model
# model.fit(train_data, y_train, epochs=10, validation_data=(test_data, y_test))
# # else:
# #     print("Target arrays 'WOPR' and 'BHP' are missing.")

In [5]:
Inpu_nms = {
    "DEPTH",
    "TRANY",
    "PORV",
    "TRANX",
    "PERMZ",
    "TRANZ",
    "PORO",
    "SATNUM",
    "PERMY",
    "PERMX",
}
data = {}


def np_load(input_nm, file_nm, rp):
    try:
        d = np.load(rp, allow_pickle=True)
        return d  # Always load data
    except ValueError as e:
        print(input_nm, file_nm, e)
        raise e


for root, dirs, files in os.walk("./origen_interview_data/", topdown=False):
    root_parts = root.split("/")
    assert len(root_parts) == 3, "too many parts in %s" % root
    input_name = root_parts[-1]

    # Process only if the input_name is in the specified set
    if input_name in Inpu_nms:
        for file in filter(".DS_Store".__ne__, files):
            file_parts = file.split(".")
            assert len(file_parts) == 2, "unexpected filename pattern: %s" % file
            dataset_name = file_parts[0]
            realpath = os.path.realpath(os.path.join(root, file))
            # Load data and store it in the dictionary
            data[input_name, dataset_name] = np_load(input_name, file, realpath)

In [6]:
def read_df(input_nm: str):
    try:
        return pd.DataFrame(
            {
                "%s_%s"
                % (input_nm.lower(), k.split("_")[0]): data[
                    input_nm, k
                ]  # Use flatten to convert 3D array to 1D
                for k in sorted(
                    [k[1] for k in data.keys() if k[0] == input_nm],
                    key=lambda x: int(x.split("_")[0][3:]),
                )
            }
        )
    except ValueError as e:
        print(input_nm, e)
        return None

In [7]:
dfs = {input_nm: read_df(input_nm) for input_nm in set([k[0] for k in data.keys()])}

In [8]:
dfs.keys()

dict_keys(['TRANZ', 'PERMZ', 'PERMX', 'DEPTH', 'TRANY', 'PORV', 'SATNUM', 'TRANX', 'PERMY', 'PORO'])

In [9]:
Inpu_nms = {
    "DEPTH",
    "TRANY",
    "PORV",
    "TRANX",
    "PERMZ",
    "TRANZ",
    "PORO",
    "SATNUM",
    "PERMY",
    "PERMX",
}

df = pd.concat(
    [
        pd.concat(
            [
                pd.DataFrame(
                    {
                        "name": [
                            k,
                        ]
                        * v.shape[0]
                    },
                    index=v.index,
                ),
                v.rename(columns={c: c.split("_")[-1] for c in v.columns}),
            ],
            axis=1,
        )
        for k, v in dfs.items()
        if k in Inpu_nms
    ]
)

df

name      sim1      sim2      sim3      sim4      sim5      sim6  \
0     TRANZ  0.159832  0.086487  0.335005  3.225324  0.099307  0.225116   
1     TRANZ  0.180607  0.106126  0.226014  2.607353  0.154976  0.195621   
2     TRANZ  0.160286  0.121656  0.147916  2.108963  0.098685  0.150983   
3     TRANZ  0.159948  0.153261  0.098632  1.340142  0.116590  0.133282   
4     TRANZ  0.161307  0.202869  0.072107  0.955459  0.111601  0.128162   
...     ...       ...       ...       ...       ...       ...       ...   
8995   PORO  0.099644  0.054589  0.445735  0.041573  0.088253  0.049302   
8996   PORO  0.107842  0.051952  0.421596  0.038334  0.082848  0.052622   
8997   PORO  0.114617  0.050342  0.409291  0.037165  0.076960  0.054312   
8998   PORO  0.117060  0.048987  0.389606  0.035103  0.071764  0.057623   
8999   PORO  0.114116  0.048962  0.384149  0.034724  0.069870  0.058801   

          sim7      sim8      sim9  ...    sim491    sim492    sim493  \
0     0.499588  0.127239  2.717454  ...  0.172920  0.415256  0.047166   
1     0.362867  0.074434  2.279546  ...  0.175326  0.572652  0.037736   
2     0.197894  0.051020  2.039845  ...  0.162570  0.705658  0.028139   
3     0.104628  0.044811  1.533976  ...  0.157798  0.802274  0.021011   
4     0.063994  0.041532  1.265849  ...  0.130385  0.833570  0.016626   
...        ...       ...       ...  ...       ...       ...       ...   
8995  0.064814  0.087458  0.054169  ...  0.043018  0.051683  0.081031   
8996  0.068861  0.096112  0.051202  ...  0.044056  0.045035  0.071682   
8997  0.074477  0.100598  0.048339  ...  0.046106  0.039736  0.065047   
8998  0.080383  0.104204  0.044099  ...  0.049697  0.038241  0.058833   
8999  0.085700  0.103141  0.040708  ...  0.058313  0.036622  0.054223   

        sim494    sim495      sim496    sim497    sim498    sim499    sim500  
0     0.248216  0.047121    0.653350  0.926199  0.009395  0.074297  0.152744  
1     0.266221  0.057708    0.821803  0.933647  0.005685  0.054261  0.107245  
2     0.251221  0.069766    1.079077  0.655371  0.004328  0.052345  0.068897  
3     0.196061  0.064618    1.508131  0.629457  0.003973  0.049913  0.048465  
4     0.114150  0.065699  215.998276  0.538419  0.004439  0.068601  0.034277  
...        ...       ...         ...       ...       ...       ...       ...  
8995  0.068500  0.051807    0.278547  0.285673  0.052007  0.091933  0.086309  
8996  0.074194  0.049902    0.253535  0.290758  0.041095  0.087402  0.086183  
8997  0.073316  0.047457    0.247300  0.295767  0.034283  0.083944  0.089724  
8998  0.070486  0.048499    0.252816  0.306163  0.028910  0.079098  0.087184  
8999  0.062973  0.051920    0.271777  0.317097  0.026862  0.072410  0.087715  

[90000 rows x 501 columns]

In [10]:
target_data = {}
target_names = {"BHP", "WOPR"}


def np_load(input_nm, file_nm, rp):
    try:
        d = np.load(rp, allow_pickle=True)
        if input_nm in target_names:  # Save data only for specified input_nm
            if input_nm in target_names:
                # d = d.reshape(15, 25, 24)
                return d
    except ValueError as e:
        print(input_nm, file_nm, e)
        raise e


for root, dirs, files in os.walk("./origen_interview_data/", topdown=False):
    root_parts = root.split("/")
    assert len(root_parts) == 3, "too many parts in %s" % root
    input_name = root_parts[-1]

    # Print "processing input" only for specified input_nm
    if input_name in target_names:
        for file in filter(".DS_Store".__ne__, files):
            file_parts = file.split(".")
            assert len(file_parts) == 2, "unexpected filename pattern: %s" % file
            dataset_name = file_parts[0]
            realpath = os.path.realpath(os.path.join(root, file))
            # Print "loading" only for specified input_nm
            # print("loading %s file %s" % (input_name, dataset_name))
            target_data[input_name, dataset_name] = np_load(input_name, file, realpath)

In [11]:
def read_df(input_nm: str):
    try:
        return pd.DataFrame(
            {
                "%s_%s" % (input_nm.lower(), k.split("_")[0]): data[input_nm, k]
                for k in sorted(
                    [k[1] for k in data.keys() if k[0] == input_nm],
                    key=lambda x: int(x.split("_")[0][3:]),
                )
            }
        )
    except ValueError as e:
        print(input_nm, e)
        return None


dfs = {input_nm: read_df(input_nm) for input_nm in set([k[0] for k in data.keys()])}


df_result = pd.concat([df for df in dfs.values()], axis=0, ignore_index=True)

In [12]:
dfs = pd.concat(
    [
        pd.concat(
            [
                pd.DataFrame(
                    {
                        "name": [
                            k,
                        ]
                        * v.shape[0]
                    },
                    index=v.index,
                ),
                v.rename(columns={c: c.split("_")[-1] for c in v.columns}),
            ],
            axis=1,
        )
        for k, v in dfs.items()
        if k in Inpu_nms
    ]
)

In [13]:
from sklearn.preprocessing import LabelEncoder

# Assuming 'name' column is categorical
label_encoder = LabelEncoder()
dfs["name_encoded"] = label_encoder.fit_transform(dfs["name"]) + 2

In [14]:
result = dfs[dfs["name_encoded"] == 11]
result

name      sim1      sim2      sim3      sim4      sim5      sim6  \
0     TRANZ  0.159832  0.086487  0.335005  3.225324  0.099307  0.225116   
1     TRANZ  0.180607  0.106126  0.226014  2.607353  0.154976  0.195621   
2     TRANZ  0.160286  0.121656  0.147916  2.108963  0.098685  0.150983   
3     TRANZ  0.159948  0.153261  0.098632  1.340142  0.116590  0.133282   
4     TRANZ  0.161307  0.202869  0.072107  0.955459  0.111601  0.128162   
...     ...       ...       ...       ...       ...       ...       ...   
8995  TRANZ  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8996  TRANZ  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8997  TRANZ  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8998  TRANZ  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8999  TRANZ  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          sim7      sim8      sim9  ...    sim492    sim493    sim494  \
0     0.499588  0.127239  2.717454  ...  0.415256  0.047166  0.248216   
1     0.362867  0.074434  2.279546  ...  0.572652  0.037736  0.266221   
2     0.197894  0.051020  2.039845  ...  0.705658  0.028139  0.251221   
3     0.104628  0.044811  1.533976  ...  0.802274  0.021011  0.196061   
4     0.063994  0.041532  1.265849  ...  0.833570  0.016626  0.114150   
...        ...       ...       ...  ...       ...       ...       ...   
8995  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
8996  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
8997  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
8998  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
8999  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   

        sim495      sim496    sim497    sim498    sim499    sim500  \
0     0.047121    0.653350  0.926199  0.009395  0.074297  0.152744   
1     0.057708    0.821803  0.933647  0.005685  0.054261  0.107245   
2     0.069766    1.079077  0.655371  0.004328  0.052345  0.068897   
3     0.064618    1.508131  0.629457  0.003973  0.049913  0.048465   
4     0.065699  215.998276  0.538419  0.004439  0.068601  0.034277   
...        ...         ...       ...       ...       ...       ...   
8995  0.000000    0.000000  0.000000  0.000000  0.000000  0.000000   
8996  0.000000    0.000000  0.000000  0.000000  0.000000  0.000000   
8997  0.000000    0.000000  0.000000  0.000000  0.000000  0.000000   
8998  0.000000    0.000000  0.000000  0.000000  0.000000  0.000000   
8999  0.000000    0.000000  0.000000  0.000000  0.000000  0.000000   

      name_encoded  
0               11  
1               11  
2               11  
3               11  
4               11  
...            ...  
8995            11  
8996            11  
8997            11  
8998            11  
8999            11  

[9000 rows x 502 columns]

In [15]:
target_data = {}
target_names = {"BHP", "WOPR"}


def np_load(input_nm, file_nm, rp):
    try:
        d = np.load(rp, allow_pickle=True)
        if input_nm in target_names:  # Save data only for specified input_nm
            if input_nm in target_names:
                # d = d.reshape(15, 25, 24)
                return d
    except ValueError as e:
        print(input_nm, file_nm, e)
        raise e


for root, dirs, files in os.walk("./origen_interview_data/", topdown=False):
    root_parts = root.split("/")
    assert len(root_parts) == 3, "too many parts in %s" % root
    input_name = root_parts[-1]

    # Print "processing input" only for specified input_nm
    if input_name in target_names:
        for file in filter(".DS_Store".__ne__, files):
            file_parts = file.split(".")
            assert len(file_parts) == 2, "unexpected filename pattern: %s" % file
            dataset_name = file_parts[0]
            realpath = os.path.realpath(os.path.join(root, file))
            # Print "loading" only for specified input_nm
            # print("loading %s file %s" % (input_name, dataset_name))
            target_data[input_name, dataset_name] = np_load(input_name, file, realpath)


df_BHP = pd.DataFrame(
    {
        "%s_%s" % ("BHP".lower(), k.split("_")[0]): target_data["BHP", k].flatten()
        for k in sorted(
            [k[1] for k in target_data.keys() if k[0] == "BHP"],
            key=lambda x: int(x.split("_")[0][3:]),
        )
    }
)

df_WOPR = pd.DataFrame(
    {
        "%s_%s" % ("WOPR".lower(), k.split("_")[0]): target_data["WOPR", k].flatten()
        for k in sorted(
            [k[1] for k in target_data.keys() if k[0] == "WOPR"],
            key=lambda x: int(x.split("_")[0][3:]),
        )
    }
)


target_df = pd.concat(
    [
        pd.concat(
            [
                pd.DataFrame(
                    {
                        "name": [
                            k,
                        ]
                        * v.shape[0]
                    },
                    index=v.index,
                ),
                v.rename(columns={c: c.split("_")[-1] for c in v.columns}),
            ],
            axis=1,
        )
        for k, v in {"WOPR": df_WOPR, "BHP": df_BHP}.items()
    ]
)


target_df.head()

name         sim1         sim2         sim3          sim4          sim5  \
0  WOPR  6759.295410    12.883436    69.527580     46.541042  15487.532227   
1  WOPR  7369.289062    16.775690    38.210709     47.645752  14446.088867   
2  WOPR  1078.612915    49.481422  4840.847656   4517.430176     19.930784   
3  WOPR  1271.152954  6392.942871  6546.472656  12025.442383     11.913373   
4  WOPR   798.250732  6898.095215  5763.392578   6471.474121     15.340807   

          sim6          sim7         sim8          sim9  ...        sim491  \
0  6104.012207    290.898193    44.279259    394.626221  ...     45.652409   
1  6451.589844  14880.507812    67.406883  28994.697266  ...  10521.727539   
2  4721.676270     63.181984  6449.222656    138.893036  ...   8899.494141   
3  4091.390137     82.429085  6786.254883    178.071655  ...  10392.467773   
4  3196.349854     43.487560  7975.293945     90.637207  ...     29.509521   

         sim492        sim493       sim494       sim495        sim496  \
0  19519.556641  13288.245117    41.505672    28.614569  11175.289062   
1  10443.629883  12160.746094  5196.479492  1779.780640   4199.051758   
2     10.858018    249.643661  4683.140137  1914.759644   2102.165039   
3      7.390196    216.625717  4951.584473  3033.915527   2662.898438   
4      3.047495    389.180176    27.644691  2718.701904   2162.393555   

         sim497      sim498       sim499       sim500  
0  10932.378906   23.241556  3651.836670  2696.564697  
1   8178.667480   15.453062  7140.892578  4355.360352  
2   5666.400879   41.717621  3721.298584  8634.990234  
3   4993.786621   33.037434  4600.001465  7435.370605  
4    147.646408  128.067841  3005.179688   118.117302  

[5 rows x 501 columns]

In [16]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
target_df["name_encoded"] = label_encoder.fit_transform(target_df["name"])
dfs_encoded = dfs.drop(columns=["name"])
target_dfs_encoded = target_df.drop(columns=["name"])
target_dfs_encoded

sim1         sim2         sim3          sim4          sim5  \
0     6759.295410    12.883436    69.527580     46.541042  15487.532227   
1     7369.289062    16.775690    38.210709     47.645752  14446.088867   
2     1078.612915    49.481422  4840.847656   4517.430176     19.930784   
3     1271.152954  6392.942871  6546.472656  12025.442383     11.913373   
4      798.250732  6898.095215  5763.392578   6471.474121     15.340807   
...           ...          ...          ...           ...           ...   
2095   400.000000  1111.188110   400.000000    671.752869    400.000000   
2096   400.000000   947.010803   400.000000    626.972717    400.000000   
2097   400.000000   994.219299   400.000000    728.786987    400.000000   
2098   400.000000   957.362122   400.000000    684.335510    400.000000   
2099   400.000000   963.475281   400.000000    647.340637    400.000000   

             sim6          sim7         sim8          sim9        sim10  ...  \
0     6104.012207    290.898193    44.279259    394.626221  1343.937988  ...   
1     6451.589844  14880.507812    67.406883  28994.697266  2586.576904  ...   
2     4721.676270     63.181984  6449.222656    138.893036  2843.940186  ...   
3     4091.390137     82.429085  6786.254883    178.071655  4784.214844  ...   
4     3196.349854     43.487560  7975.293945     90.637207  5118.585938  ...   
...           ...           ...          ...           ...          ...  ...   
2095  1078.145264    400.000000   400.000000    400.000000  1053.112427  ...   
2096  1100.261108    400.000000   400.000000    400.000000  1052.021118  ...   
2097  1270.876709    400.000000   400.000000    400.000000  1070.278442  ...   
2098  1217.312012    400.000000   400.000000    400.000000  1024.680664  ...   
2099  1301.798828    400.000000   400.000000    400.000000  1055.230469  ...   

            sim492        sim493       sim494       sim495        sim496  \
0     19519.556641  13288.245117    41.505672    28.614569  11175.289062   
1     10443.629883  12160.746094  5196.479492  1779.780640   4199.051758   
2        10.858018    249.643661  4683.140137  1914.759644   2102.165039   
3         7.390196    216.625717  4951.584473  3033.915527   2662.898438   
4         3.047495    389.180176    27.644691  2718.701904   2162.393555   
...            ...           ...          ...          ...           ...   
2095    400.000000    400.000000   400.000000  1597.291260   1260.779907   
2096    400.000000    400.000000   400.000000  1589.765015   1273.591431   
2097    400.000000    400.000000   400.000000  1644.383057   1335.386719   
2098    400.000000    400.000000   400.000000  1578.907104   1255.956299   
2099    400.000000    400.000000   400.000000  1584.662476   1315.279541   

            sim497      sim498       sim499       sim500  name_encoded  
0     10932.378906   23.241556  3651.836670  2696.564697             1  
1      8178.667480   15.453062  7140.892578  4355.360352             1  
2      5666.400879   41.717621  3721.298584  8634.990234             1  
3      4993.786621   33.037434  4600.001465  7435.370605             1  
4       147.646408  128.067841  3005.179688   118.117302             1  
...            ...         ...          ...          ...           ...  
2095    400.000000  400.000000   400.000000   400.000000             0  
2096    400.000000  400.000000   400.000000   400.000000             0  
2097    400.000000  400.000000   400.000000   400.000000             0  
2098    400.000000  400.000000   400.000000   400.000000             0  
2099    400.000000  400.000000   400.000000   400.000000             0  

[4200 rows x 501 columns]

In [17]:
df_t = dfs_encoded.transpose()
print(df_t.shape)
target_df_t = target_dfs_encoded.transpose()
target_df_t.shape

(501, 90000)


(501, 4200)

In [ ]:
from absl import flags
from datetime import datetime
import numpy as np
import random
from os.path import join as pjoin
import torch
import tensorflow as tf
from tensorflow.keras.layers import GaussianNoise, LSTM, Dropout, Dense

from tensorflow.keras.layers import Flatten


FLAGS = flags.FLAGS

# Mark the flags as parsed to prevent duplicate definition error
flags.DEFINE_string(
    "TARGET_WELL", default="default_value", help="Description of TARGET_WELL"
)
flags.DEFINE_integer("EPOCHS", default=10, help="Number of training epochs")
flags.DEFINE_integer("BATCH_SIZE", default=32, help="Batch size for training")

FLAGS.mark_as_parsed()


def _get_log_path():
    return pjoin("logs", f"well_{FLAGS.TARGET_WELL}")


def main(argv=None):
    random.seed(7)

    def get_model(params):
        input_shape = params["input_shape"]
        lstm1_units = params["lstm1_units"]
        lstm2_units = params["lstm2_units"]
        gaussian_std = params["gaussian_std"]
        dropout_rate = params["dropout_rate"]
        optimizer = params["optimizer"]
        loss = params["loss"]

        model = tf.keras.models.Sequential()
        model.add(GaussianNoise(gaussian_std, input_shape=input_shape))

        model.add(LSTM(lstm1_units, activation="relu", return_sequences=True))
        model.add(Dropout(dropout_rate))

        model.add(LSTM(lstm2_units, activation="relu", return_sequences=True))
        model.add(Dropout(dropout_rate))
        model.add(Flatten())

        # Equivalent to nn.Linear(90000, 256)
        model.add(Dense(256, activation="relu"))

        # Equivalent to nn.Linear(256, 4200)
        model.add(Dense(4200, activation="linear"))

        model.compile(optimizer=optimizer, loss=loss)

        model.summary()

        return model

    # Specify the indices for training, testing, and validation
    train_indices = range(0, 450)
    test_indices = range(450, 475)
    val_indices = range(475, 500)

    df_input = df_t
    df_targets = target_df_t
    # processor.remove_zero_wopr(well)

    # Convert DataFrames to PyTorch tensors
    input_data = torch.tensor(df_input.values, dtype=torch.float32)
    targets = torch.tensor(df_targets.values, dtype=torch.float32)

    # Split the data into training, testing, and validation sets
    input_train, targets_train = input_data[train_indices], targets[train_indices]
    input_test, targets_test = input_data[test_indices], targets[test_indices]
    input_val, targets_val = input_data[val_indices], targets[val_indices]

    # Convert NumPy arrays to PyTorch tensors
    train_x = input_train.clone().detach()
    train_y = targets_train.clone().detach()
    val_x = input_val.clone().detach()
    test_x = input_test.clone().detach()

    train_y = targets_train.clone().detach()
    val_y = targets_val.clone().detach()
    test_y = targets_test.clone().detach()

    train_data = torch.utils.data.TensorDataset(train_x, train_y)
    train_loader = torch.utils.data.DataLoader(
        train_data, batch_size=FLAGS.BATCH_SIZE, shuffle=True
    )

    val_data = torch.utils.data.TensorDataset(val_x, val_y)
    val_loader = torch.utils.data.DataLoader(
        val_data, batch_size=FLAGS.BATCH_SIZE, shuffle=False
    )

    # Convert PyTorch tensors to NumPy arrays
    train_x_numpy = train_x.numpy()
    train_y_numpy = train_y.numpy()
    val_x_numpy = val_x.numpy()
    val_y_numpy = val_y.numpy()

    lstm_model = get_model(
        params={
            "input_shape": (
                train_x_numpy.shape[1],
                1,
            ),  # Assuming each feature corresponds to a time step
            "lstm1_units": 50,
            "lstm2_units": 50,
            "gaussian_std": 0.1,
            "dropout_rate": 0.2,
            "optimizer": "adam",
            "loss": "mean_squared_error",
        }
    )

    latest = tf.train.latest_checkpoint(_get_log_path())
    print(f"latest checkpoint: {latest}")
    if latest is not None:
        print("Restoring trained weights")
        lstm_model.load_weights(latest)
    else:
        for epoch in range(FLAGS.EPOCHS):
            for batch_x, batch_y in train_loader:
                # Convert PyTorch tensors to NumPy arrays for each batch
                batch_x_numpy = batch_x.numpy()
                batch_y_numpy = batch_y.numpy()

                print("Batch X shape:", batch_x.shape)
                print("Batch Y shape:", batch_y.shape)
                # Train the model on the current batch
                history = lstm_model.train_on_batch(batch_x_numpy, batch_y_numpy)

    es = tf.keras.callbacks.EarlyStopping(
        monitor="val_loss", mode="min", patience=6, verbose=1
    )
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    logdir = pjoin(_get_log_path(), "scalars")
    tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=logdir)
    checkpoint_path = pjoin(_get_log_path(), "model.ckpt-{epoch:04d}")
    checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
        filepath=checkpoint_path, save_weights_only=True, verbose=1
    )

    latest = tf.train.latest_checkpoint(_get_log_path())
    print(f"latest checkpoint: {latest}")
    if latest is not None:
        print("Restoring trained weights")
        lstm_model.load_weights(latest)
    else:
        history = lstm_model.fit(
            train_loader,
            epochs=FLAGS.EPOCHS,
            validation_data=val_loader,
            use_multiprocessing=True,
            workers=8,
            callbacks=[es, tensorboard_callback],
        )
        print("training has been ended")

        lstm_model.save_weights(checkpoint_path.format(epoch=FLAGS.EPOCHS))
        print("model weights are saved")
        np.save(
            pjoin(_get_result_path(), f"ground_truth_{timestamp}.npy"), test_y.numpy()
        )
        print("Ground Truth is saved...")

    def cascade_inference(model, test_x, test_y, obs, gaussian_std):
        y_hat_list = []
        observed = test_y[:obs]
        y_hat_list.extend(observed)

        buffer = test_x[obs : obs + 1]
        mu = gaussian_std

        for i in range(obs + 1, test_x.shape[0]):
            y_hat = model.predict(buffer)
            predicted_val = y_hat[0, 0, 0]
            y_hat_list.append(predicted_val)

            buffer = np.delete(buffer, 0, 1)
            next_wbhp = test_x[i : i + 1][0, 4, 1]
            predicted_array = np.array([[predicted_val, next_wbhp]])

            buffer = np.vstack((buffer[0], predicted_array))
            buffer = np.reshape(buffer, (1, 5, 2))

            mean_wopr = np.mean(buffer[0], axis=0)[0]
            mean_wbhp = np.mean(buffer[0], axis=0)[1]
            wopr_predicted_noise_added = np.random.normal(mean_wopr, mu, 1)
            wbhp_predicted_noise_added = np.random.normal(mean_wbhp, mu, 1)

            buffer[0, 4, 0] = wopr_predicted_noise_added
            buffer[0, 4, 1] = wbhp_predicted_noise_added

        return y_hat_list

    ## Inference
    y_hat_list = cascade_inference(
        lstm_model,
        test_x.numpy(),
        test_y.numpy(),
        obs=FLAGS.OBSERVATION_DATE,
        gaussian_std=FLAGS.INFERENCE_GAUSSIAN_STD,
    )
    print("Saving inference results...")
    np.save(pjoin(_get_result_path(), f"inference_result_{timestamp}.npy"), y_hat_list)
    print("Saving prediction graph...")
    save_prediction(
        y_hat_list,
        test_y.numpy(),
        f"Prediction {FLAGS.TARGET_WELL}, true model: {FLAGS.TRUE_MODEL}",
        timestamp,
    )


if __name__ == "__main__":
    main()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gaussian_noise (GaussianNo  (None, 90000, 1)          0         
 ise)                                                            
                                                                 
 lstm (LSTM)                 (None, 90000, 50)         10400     
                                                                 
 dropout (Dropout)           (None, 90000, 50)         0         
                                                                 
 lstm_1 (LSTM)               (None, 90000, 50)         20200     
                                                                 
 dropout_1 (Dropout)         (None, 90000, 50)         0         
                                                                 
 flatten (Flatten)           (None, 4500000)           0         
                                                        

In [ ]:
train_indices = range(0, 450)
test_indices = range(450, 475)
val_indices = range(475, 500)

df_input = df_t
df_targets = target_df_t
# processor.remove_zero_wopr(well)

# Convert DataFrames to PyTorch tensors
input_data = torch.tensor(df_input.values, dtype=torch.float32)
targets = torch.tensor(df_targets.values, dtype=torch.float32)

# Split the data into training, testing, and validation sets
input_train, targets_train = input_data[train_indices], targets[train_indices]
input_test, targets_test = input_data[test_indices], targets[test_indices]
input_val, targets_val = input_data[val_indices], targets[val_indices]


# Convert NumPy arrays to PyTorch tensors
train_x = torch.tensor(input_train, dtype=torch.float32)
train_x.shape[2]

In [22]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Assuming df_input and df_targets are your input and target DataFrames
# Make sure to replace these with your actual data

# Specify the indices for training, testing, and validation
train_indices = range(0, 450)
test_indices = range(450, 475)
val_indices = range(475, 500)

df_input = df_t
df_targets = target_df_t

# Convert DataFrames to PyTorch tensors
input_data = torch.tensor(df_input.values, dtype=torch.float32)
targets = torch.tensor(df_targets.values, dtype=torch.float32)

# Split the data into training, testing, and validation sets
input_train, targets_train = input_data[train_indices], targets[train_indices]
input_test, targets_test = input_data[test_indices], targets[test_indices]
input_val, targets_val = input_data[val_indices], targets[val_indices]


# Define a simple neural network model
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(90000, 256)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(256, 4200)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x


# Instantiate the model, loss function, and optimizer
model = SimpleNN()
criterion = nn.MSELoss()  # Mean Squared Error Loss for regression task
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Convert data to PyTorch DataLoader for batch processing
train_dataset = TensorDataset(input_train, targets_train)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Train the model
num_epochs = 10
for epoch in range(num_epochs):
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item()}")

# Evaluate the model on the validation set
model.eval()
with torch.no_grad():
    val_outputs = model(input_val)
    val_loss = criterion(val_outputs, targets_val)
    print(f"Validation Loss: {val_loss.item()}")

Epoch 1/10, Loss: 8324177.0
Epoch 2/10, Loss: 8716083.0
Epoch 3/10, Loss: 13565817.0
Epoch 4/10, Loss: 4600601.5
Epoch 5/10, Loss: 17100200.0
Epoch 6/10, Loss: 12213555.0
Epoch 7/10, Loss: 8107389.0
Epoch 8/10, Loss: 8471522.0
Epoch 9/10, Loss: 3430586.25
Epoch 10/10, Loss: 9344926.0
Validation Loss: 8621179.0


In [23]:
import torch.nn.functional as F
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Assuming df_input and df_targets are your input and target DataFrames
# Make sure to replace these with your actual data

# Specify the indices for training, testing, and validation
train_indices = range(0, 450)
test_indices = range(450, 475)
val_indices = range(475, 500)

df_input = df_t
df_targets = target_df_t

# Convert DataFrames to PyTorch tensors
input_data = torch.tensor(df_input.values, dtype=torch.float32)
targets = torch.tensor(df_targets.values, dtype=torch.float32)

# Split the data into training, testing, and validation sets
input_train, targets_train = input_data[train_indices], targets[train_indices]
input_test, targets_test = input_data[test_indices], targets[test_indices]
input_val, targets_val = input_data[val_indices], targets[val_indices]


class ComplexNN(nn.Module):
    def __init__(self):
        super(ComplexNN, self).__init__()
        self.fc1 = nn.Linear(90000, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, 128)
        self.fc4 = nn.Linear(128, 64)
        self.fc5 = nn.Linear(64, 4200)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.5)
        self.batch_norm1 = nn.BatchNorm1d(512)
        self.batch_norm2 = nn.BatchNorm1d(256)
        self.batch_norm3 = nn.BatchNorm1d(128)

    def forward(self, x):
        x = self.fc1(x)
        x = self.batch_norm1(x)
        x = self.relu(x)
        x = self.dropout(x)

        x = self.fc2(x)
        x = self.batch_norm2(x)
        x = self.relu(x)
        x = self.dropout(x)

        x = self.fc3(x)
        x = self.batch_norm3(x)
        x = self.relu(x)
        x = self.dropout(x)

        x = self.fc4(x)
        x = self.relu(x)
        x = self.dropout(x)

        x = self.fc5(x)
        return x


# Instantiate the model, loss function, and optimizer
model = SimpleNN()
criterion = nn.MSELoss()  # Mean Squared Error Loss for regression task
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Convert data to PyTorch DataLoader for batch processing
train_dataset = TensorDataset(input_train, targets_train)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Train the model
num_epochs = 10
for epoch in range(num_epochs):
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item()}")

# Evaluate the model on the validation set
model.eval()
with torch.no_grad():
    val_outputs = model(input_val)
    val_loss = criterion(val_outputs, targets_val)
    print(f"Validation Loss: {val_loss.item()}")

Epoch 1/10, Loss: 170766.46875
Epoch 2/10, Loss: 11259673.0
Epoch 3/10, Loss: 10776707.0
Epoch 4/10, Loss: 7760842.5
Epoch 5/10, Loss: 5403753.5
Epoch 6/10, Loss: 12070947.0
Epoch 7/10, Loss: 10437511.0
Epoch 8/10, Loss: 11117633.0
Epoch 9/10, Loss: 6633403.0
Epoch 10/10, Loss: 9259043.0
Validation Loss: 8621116.0


In [45]:
9259043.0 - 6633403.0

2625640.0

In [44]:
import shap
import numpy as np
import torch
from sklearn.ensemble import RandomForestRegressor


train_indices = range(0, 10)
# test_indices = range(450, 475)
# val_indices = range(475, 500)

# df_input = df_t
# df_targets = target_df_t
df_input = df_t.iloc[:50, :]
df_targets = target_df_t.iloc[:50]

# Convert DataFrames to PyTorch tensors
input_data = torch.tensor(df_input.values, dtype=torch.float32)
targets = torch.tensor(df_targets.values, dtype=torch.float32)

# Split the data into training, testing, and validation sets
input_train, targets_train = input_data[train_indices], targets[train_indices]
# input_test, targets_test = input_data[test_indices], targets[test_indices]
# input_val, targets_val = input_data[val_indices], targets[val_indices]

model = RandomForestRegressor()
model.fit(
    input_train, targets_train
)  # Replace df_input and df_targets with your actual training data

# Create a SHAP explainer
explainer = shap.TreeExplainer(model)

# Calculate SHAP values for a sample of your data
sample_idx = 0  # You can choose any index from your dataset
sample = df_input.iloc[sample_idx, :]  # Assuming df_input is your input DataFrame
sample = sample.values.reshape(1, -1)
shap_values = explainer.shap_values(sample)

# Summarize the feature importance
shap.summary_plot(shap_values, df_input)

Creating legend with loc="best" can be slow with large amounts of data.
Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all axes decorations.
Creating legend with loc="best" can be slow with large amounts of data.


ValueError: Image size of 695x110633 pixels is too large. It must be less than 2^16 in each direction.

<Figure size 800x950 with 1 Axes>

In [46]:
shap_values

[array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0.,

In [ ]:
import numpy as np
import random
import time
import qri
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers.core import Activation, Dense, Dropout
from keras.models import Sequential
from keras.optimizers import SGD
import sys

# If you want to pass an argument when running the script, uncomment the following lines
# if len(sys.argv) > 1:
#     first = int(sys.argv[1])
# else:
#     first = <your_default_value>

# Model name
MDL_NAME = "fcn-a-3hidden-thick%s" % first  # Assuming 'first' is defined

# Seed random number generator
np.random.seed(42)

# Load your specific data (replace 'your_data.pkl.gz' with the actual file path)
datasets = qri.load_data("your_data.pkl.gz")

# Split into 2D datasets
train_set, valid_set, test_set = datasets

# Build neural network
model = Sequential()
model.add(Dense(48, input_shape=(first,), activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(first, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(first, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(12))

# Use stochastic gradient descent and compile the model
sgd = SGD(lr=0.001, momentum=0.99, decay=1e-6, nesterov=True)
model.compile(loss=qri.mae_clip, optimizer=sgd)

# Use early stopping and saving as callbacks
early_stop = EarlyStopping(monitor="val_loss", patience=10)
save_best = ModelCheckpoint("models/%s.mdl" % MDL_NAME, save_best_only=True)
callbacks = [early_stop, save_best]

# Train the model
t0 = time.time()
hist = model.fit(
    train_set[0],
    train_set[1],
    validation_data=valid_set,
    verbose=2,
    callbacks=callbacks,
    epochs=1000,
    batch_size=10,
)
time_elapsed = time.time() - t0

# Load the best model
model.load_weights("models/%s.mdl" % MDL_NAME)

# Print time elapsed and loss on the testing dataset
test_set_loss = model.evaluate(test_set[0], test_set[1])
print("\nTime elapsed: %f s" % time_elapsed)
print("Testing set loss: %f" % test_set_loss)

# Save results
qri.save_results("results/%s.out" % MDL_NAME, time_elapsed, test_set_loss)
# qri.save_history("models/%s.hist" % MDL_NAME, hist.history)

# Plot training and validation loss
# qri.plot_train_valid_loss(hist.history)

# Make predictions
# qri.plot_test_predictions(model, train_set)

In [329]:
target_dfs_encoded.shape

(4200, 501)

In [116]:
dfs_encoded.shape

(90000, 501)

In [21]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Assuming df_input and df_targets are your input and target DataFrames
# Make sure to replace these with your actual data

df_input = df_t
df_targets = target_df_t
# label_encoder = LabelEncoder()
# df_encoded['name'] = label_encoder.fit_transform(df_input['name'])

# Convert DataFrames to PyTorch tensors
input_data = torch.tensor(df_input.values, dtype=torch.float32)
targets = torch.tensor(df_targets.values, dtype=torch.float32)

# Split the data into training and validation sets
input_train, input_val, targets_train, targets_val = train_test_split(
    input_data, targets, test_size=0.2, random_state=42
)


# Define a simple neural network model
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(90000, 256)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(256, 4200)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x


# Instantiate the model, loss function, and optimizer
model = SimpleNN()
criterion = nn.MSELoss()  # Mean Squared Error Loss for regression task
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Convert data to PyTorch DataLoader for batch processing
train_dataset = TensorDataset(input_train, targets_train)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Train the model
num_epochs = 10
for epoch in range(num_epochs):
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item()}")

# Evaluate the model on the validation set
model.eval()
with torch.no_grad():
    val_outputs = model(input_val)
    val_loss = criterion(val_outputs, targets_val)
    print(f"Validation Loss: {val_loss.item()}")

Epoch 1/10, Loss: 9803272.0
Epoch 2/10, Loss: 7832621.5
Epoch 3/10, Loss: 8496736.0
Epoch 4/10, Loss: 8261475.0
Epoch 5/10, Loss: 7251770.0
Epoch 6/10, Loss: 7898776.0
Epoch 7/10, Loss: 8564776.0
Epoch 8/10, Loss: 9317698.0
Epoch 9/10, Loss: 9487942.0
Epoch 10/10, Loss: 8700524.0
Validation Loss: 9418390.0


In [232]:
num_samples = target_dfs_encoded.shape[0]

# Create a random permutation of indices
np.random.seed(42)

# Randomly sample rows from dfs_encoded and target_dfs_encoded
sampled_dfs = dfs_encoded.sample(n=num_samples, random_state=42)
sampled_target_dfs = target_dfs_encoded.sample(n=num_samples, random_state=42)


lreg = LinearRegression()
rfe = RFE(lreg)
rfe.n_features_to_select = 300  # Replace 10 with the desired number of features
X_rfe = rfe.fit_transform(sampled_dfs, sampled_target_dfs)

X_rfe = rfe.transform(dfs_encoded)
X_target_rfe = rfe.transform(target_dfs_encoded)

In [293]:
import shap
import numpy as np
from sklearn.ensemble import RandomForestRegressor

# Assume you have a trained model (replace this with your actual model)
model = RandomForestRegressor()

model.fit(sampled_dfs, sampled_target_dfs)

# Create a SHAP explainer
explainer = shap.TreeExplainer(model)

# Calculate SHAP values for a sample of your data
sample_idx = 0  # You can choose any index from your dataset
sample = X_train[sample_idx]
sample = sample.reshape(1, -1)
shap_values = explainer.shap_values(sample)

# Summarize the feature importance
shap.summary_plot(shap_values, X_train)

ValueError: could not convert string to float: 'TRANY'

In [50]:
import numpy as np
import random
import time
import qri
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers.core import Activation, Dense, Dropout
from keras.models import Sequential
from keras.optimizers import SGD
import sys

# If you want to pass an argument when running the script, uncomment the following lines
# if len(sys.argv) > 1:
#     first = int(sys.argv[1])
# else:
#     first = <your_default_value>

# Model name
MDL_NAME = "fcn-a-3hidden-thick%s" % first  # Assuming 'first' is defined

# Seed random number generator
np.random.seed(42)

# Load your specific data (replace 'your_data.pkl.gz' with the actual file path)
datasets = qri.load_data("your_data.pkl.gz")

# Split into 2D datasets
train_set, valid_set, test_set = datasets

# Build neural network
model = Sequential()
model.add(Dense(48, input_shape=(first,), activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(first, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(first, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(12))

# Use stochastic gradient descent and compile the model
sgd = SGD(lr=0.001, momentum=0.99, decay=1e-6, nesterov=True)
model.compile(loss=qri.mae_clip, optimizer=sgd)

# Use early stopping and saving as callbacks
early_stop = EarlyStopping(monitor="val_loss", patience=10)
save_best = ModelCheckpoint("models/%s.mdl" % MDL_NAME, save_best_only=True)
callbacks = [early_stop, save_best]

# Train the model
t0 = time.time()
hist = model.fit(
    train_set[0],
    train_set[1],
    validation_data=valid_set,
    verbose=2,
    callbacks=callbacks,
    epochs=1000,
    batch_size=10,
)
time_elapsed = time.time() - t0

# Load the best model
model.load_weights("models/%s.mdl" % MDL_NAME)

# Print time elapsed and loss on the testing dataset
test_set_loss = model.evaluate(test_set[0], test_set[1])
print("\nTime elapsed: %f s" % time_elapsed)
print("Testing set loss: %f" % test_set_loss)

# Save results
qri.save_results("results/%s.out" % MDL_NAME, time_elapsed, test_set_loss)
# qri.save_history("models/%s.hist" % MDL_NAME, hist.history)

# Plot training and validation loss
# qri.plot_train_valid_loss(hist.history)

# Make predictions
# qri.plot_test_predictions(model, train_set)

ModuleNotFoundError: No module named 'qri'

In [26]:
mydict = {"hello": "world", 1: 2}

In [27]:
mydict

{'hello': 'world', 1: 2}

In [28]:
mydict.keys()

dict_keys(['hello', 1])

In [29]:
mydict.values()

dict_values(['world', 2])

In [31]:
for k, v in mydict.items():
    print("key: %s, value: %s" % (k, v))

key: hello, value: world
key: 1, value: 2
